pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'dotnet-jenkins-image'
        GITHUB_REPO = 'https://github.com/Abitdavy/dotnet-jenkins.git'
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                            git config --global credential.helper store
                            echo "https://${GITHUB_TOKEN}:@github.com" > ~/.git-credentials
                            git clone https://github.com/Abitdavy/dotnet-jenkins.git .
                            cd dotnet-jenkins
                        '''
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}", "dotnet-jenkins")
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    docker.image("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}").run('-d -p 8081:80')
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}