pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'dotnet-jenkins-image'
        GITHUB_REPO = 'https://github.com/Abitdavy/dotnet-jenkins.git'
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Ensure the workspace is clean
                    sh 'rm -rf dotnet-jenkins || true'
                    
                    // Clone the repository securely
                    withCredentials([string(credentialsId: 'github-secret-token', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                            git clone https://${GITHUB_TOKEN}@github.com/Abitdavy/dotnet-jenkins.git
                        '''
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    // Specify the path to Dockerfile and build context directory
                    docker.build("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}", "-f dotnet-jenkins/Dockerfile dotnet-jenkins")
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    // Run the Docker container
                    // Map container port 80 to host port 8081
                    docker.image("${env.DOCKER_IMAGE}:${env.BUILD_NUMBER}").run('-d -p 8081:80')
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}